const aTypes = {
    MAIN_BLOCK_SHOW: 'MAIN_BLOCK_SHOW',
    MATERIAL_OPTIONS_BLOCK_SHOW: 'MATERIAL_OPTIONS_BLOCK_SHOW',
    TEST_OPTIONS_BLOCK_SHOW: 'TEST_OPTIONS_BLOCK_SHOW',
    COURSE_OPTIONS_BLOCK_SHOW: 'COURSE_OPTIONS_BLOCK_SHOW',
};

export default aTypes;