const aTypes = {
    AUTH_MODAL_OPEN: 'AUTH_MODAL_OPEN',
    AUTH_MODAL_CLOSE: 'AUTH_MODAL_CLOSE',
    AUTH_USER_IS_LOGGED: 'AUTH_USER_IS_LOGGED',
    AUTH_USER_IS_LOGOUT: 'AUTH_USER_IS_LOGOUT',
    REGISTER_FORM_OPEN: 'REGISTER_FORM_OPEN',
    REGISTER_FORM_CLOSE: 'REGISTER_FORM_CLOSE',
    FORGOT_PASSWORD_MODAL_OPEN: 'FORGOT_PASSWORD_MODAL_OPEN',
    FORGOT_PASSWORD_MODAL_CLOSE: 'FORGOT_PASSWORD_MODAL_CLOSE',
    HEADER_GET_DATA: 'HEADER_GET_DATA',
    HEADER_GET_DATA_FULFILL: 'HEADER_GET_DATA_FULFILL',
    SEND_REFRESH_TOKEN_TO_AUTH: 'SEND_REFRESH_TOKEN_TO_AUTH',
};

export default aTypes;