const aTypes = {
    REGISTER_NAME_FIELD_CHANGE: 'REGISTER_NAME_FIELD_CHANGE',
    REGISTER_EMAIL_FIELD_CHANGE: 'REGISTER_EMAIL_FIELD_CHANGE',
    REGISTER_PASSWORD_FIELD_CHANGE: 'REGISTER_PASSWORD_FIELD_CHANGE',
    REGISTER_PASSWORD_REPEAT_FIELD_CHANGE: 'REGISTER_PASSWORD_REPEAT_FIELD_CHANGE',
    REGISTER_NAME_FIELD_BLUR: 'REGISTER_NAME_FIELD_BLUR',
    REGISTER_EMAIL_FIELD_BLUR: 'REGISTER_EMAIL_FIELD_BLUR',
    REGISTER_PASSWORD_FIELD_BLUR: 'REGISTER_PASSWORD_FIELD_BLUR',
    REGISTER_PASSWORD_FIELD_REPEAT_BLUR: 'REGISTER_PASSWORD_FIELD_REPEAT_BLUR',
    REGISTER_CLEAR_NAME_ERROR_MESSAGE: 'REGISTER_CLEAR_NAME_ERROR_MESSAGE',
    REGISTER_CLEAR_EMAIL_ERROR_MESSAGE: 'REGISTER_CLEAR_EMAIL_ERROR_MESSAGE',
    REGISTER_CLEAR_PASSWORD_ERROR_MESSAGE: 'REGISTER_CLEAR_PASSWORD_ERROR_MESSAGE',
    REGISTER_CLEAR_PASSWORD_REPEAT_ERROR_MESSAGE: 'REGISTER_CLEAR_PASSWORD_REPEAT_ERROR_MESSAGE',
    REGISTER_CLEAR_FIELDS: 'REGISTER_CLEAR_FIELDS',
    SEND_REQUEST_FOR_REGISTER: 'SEND_REQUEST_FOR_REGISTER',
    SEND_REQUEST_FOR_REGISTER_REJECT: 'SEND_REQUEST_FOR_REGISTER_REJECT',
    REGISTER_FORM_CLOSE: 'REGISTER_FORM_CLOSE',
    AUTH_USER_IS_LOGGED: 'AUTH_USER_IS_LOGGED',
    HEADER_GET_DATA: 'HEADER_GET_DATA',
    REGISTER_MODAL_LOADING: 'REGISTER_MODAL_LOADING',
    REGISTER_MODAL_LOADING_REJECT: 'REGISTER_MODAL_LOADING_REJECT',
};

export default aTypes;