const aTypes = {
    FORGOT_PASSWORD_MODAL_OPEN: 'FORGOT_PASSWORD_MODAL_OPEN',
    FORGOT_PASSWORD_MODAL_CLOSE: 'FORGOT_PASSWORD_MODAL_CLOSE',
    EMAIL_FIELD_BLUR: 'EMAIL_FIELD_BLUR',
};

export default aTypes;