const aTypes = {
    AUTH_MODAL_OPEN: 'AUTH_MODAL_OPEN',
    AUTH_MODAL_CLOSE: 'AUTH_MODAL_CLOSE',
    REGISTER_FORM_OPEN: 'REGISTER_FORM_OPEN',
    REGISTER_FORM_CLOSE: 'REGISTER_FORM_CLOSE',
    FORGOT_PASSWORD_MODAL_OPEN: 'FORGOT_PASSWORD_MODAL_OPEN',
    FORGOT_PASSWORD_MODAL_CLOSE: 'FORGOT_PASSWORD_MODAL_CLOSE',
};

export default aTypes;