const aTypes = {
    REGISTER_FORM_OPEN: 'REGISTER_FORM_OPEN',
    REGISTER_FORM_CLOSE: 'REGISTER_FORM_CLOSE',
    NAME_FIELD_BLUR: 'NAME_FIELD_BLUR',
    EMAIL_FIELD_BLUR: 'EMAIL_FIELD_BLUR',
    PASSWORD_FIELD_BLUR: 'PASSWORD_FIELD_BLUR',
    PASSWORD_FIELD_REPEAT_BLUR: 'PASSWORD_FIELD_REPEAT_BLUR',
    CLEAR_NAME_ERROR_MESSAGE: 'CLEAR_NAME_ERROR_MESSAGE',
    CLEAR_EMAIL_ERROR_MESSAGE: 'CLEAR_EMAIL_ERROR_MESSAGE',
    CLEAR_PASSWORD_ERROR_MESSAGE: 'CLEAR_PASSWORD_ERROR_MESSAGE',
    CLEAR_PASSWORD_REPEAT_ERROR_MESSAGE: 'CLEAR_PASSWORD_REPEAT_ERROR_MESSAGE',
};

export default aTypes;