const aTypes = {
    REGISTER_NAME_FIELD_CHANGE: 'REGISTER_NAME_FIELD_CHANGE',
    REGISTER_EMAIL_FIELD_CHANGE: 'REGISTER_EMAIL_FIELD_CHANGE',
    REGISTER_PASSWORD_FIELD_CHANGE: 'REGISTER_PASSWORD_FIELD_CHANGE',
    REGISTER_PASSWORD_REPEAT_FIELD_CHANGE: 'REGISTER_PASSWORD_REPEAT_FIELD_CHANGE',
    REGISTER_NAME_FIELD_BLUR: 'REGISTER_NAME_FIELD_BLUR',
    REGISTER_EMAIL_FIELD_BLUR: 'REGISTER_EMAIL_FIELD_BLUR',
    REGISTER_PASSWORD_FIELD_BLUR: 'REGISTER_PASSWORD_FIELD_BLUR',
    REGISTER_PASSWORD_FIELD_REPEAT_BLUR: 'REGISTER_PASSWORD_FIELD_REPEAT_BLUR',
    REGISTER_CLEAR_NAME_ERROR_MESSAGE: 'REGISTER_CLEAR_NAME_ERROR_MESSAGE',
    REGISTER_CLEAR_EMAIL_ERROR_MESSAGE: 'REGISTER_CLEAR_EMAIL_ERROR_MESSAGE',
    REGISTER_CLEAR_PASSWORD_ERROR_MESSAGE: 'REGISTER_CLEAR_PASSWORD_ERROR_MESSAGE',
    REGISTER_CLEAR_PASSWORD_REPEAT_ERROR_MESSAGE: 'REGISTER_CLEAR_PASSWORD_REPEAT_ERROR_MESSAGE',
};

export default aTypes;