const aTypes = {
    REGISTER_OPEN: 'REGISTER_OPEN',
    REGISTER_OPEN_FULFILLED: 'REGISTER_OPEN_FULFILLED',
    REGISTER_OPEN_REJECTED: 'REGISTER_OPEN_REJECTED',
    REGISTER_CLOSE: 'REGISTER_CLOSE',
    REGISTER_CLOSE_FULFILLED: 'REGISTER_CLOSE_FULFILLED',
    REGISTER_CLOSE_REJECTED: 'REGISTER_CLOSE_REJECTED',
    FORM_FIELDS_UPDATE: 'FORM_FIELDS_UPDATE',
    FORM_FIELDS_UPDATE_FULFILLED: 'FORM_FIELDS_UPDATE_FULFILLED',
    FORM_FIELDS_UPDATE_REJECTED: 'FORM_FIELDS_UPDATE_REJECTED',
};

export default aTypes;