const aType = {
    SEND_REQUEST_FOR_AUTH: 'SEND_REQUEST_FOR_AUTH',
    SEND_REQUEST_FOR_REGISTER: 'SEND_REQUEST_FOR_REGISTER',
    AUTH_MODAL_CLOSE: 'AUTH_MODAL_CLOSE',
    REGISTER_FORM_CLOSE: 'REGISTER_FORM_CLOSE',
    AUTH_CLEAR_FIELDS: 'AUTH_CLEAR_FIELDS',
    REGISTER_CLEAR_FIELDS: 'REGISTER_CLEAR_FIELDS',
    RECEIVED_ERROR_AUTH: 'RECEIVED_ERROR_AUTH',
    RECEIVED_ERROR_REGISTER: 'RECEIVED_ERROR_REGISTER',
    RECEIVED_ERROR_RESTORE_PASS: 'RECEIVED_ERROR_RESTORE_PASS',
};

export default aType;