const aType = {
    SEND_REFRESH_TOKEN_TO_AUTH: 'SEND_REFRESH_TOKEN_TO_AUTH',
    SEND_REFRESH_TOKEN_TO_AUTH_REJECT: 'SEND_REFRESH_TOKEN_TO_AUTH_REJECT',
    AUTH_MODAL_OPEN: 'AUTH_MODAL_OPEN',
    AUTH_USER_IS_LOGOUT: 'AUTH_USER_IS_LOGOUT',
};

export default aType;