const aTypes = {
    GET_VOCABULARY_WORDS_SET: 'GET_VOCABULARY_WORDS_SET',
    VOCABULARY_GO_TO_NEXT_WORD: 'VOCABULARY_GO_TO_NEXT_WORD',
    RECORD_USER_ANSWER: 'RECORD_USER_ANSWER',
};

export default aTypes;