const aTypes = {
    GET_VOCABULARY_WORDS_SET: 'GET_VOCABULARY_WORDS_SET',
    GET_VOCABULARY_WORDS_SET_FULFILLED: 'GET_VOCABULARY_WORDS_SET_FULFILLED',
    GET_VOCABULARY_WORDS_SET_REJECT: 'GET_VOCABULARY_WORDS_SET_REJECT',
    VOCABULARY_GO_TO_NEXT_WORD: 'VOCABULARY_GO_TO_NEXT_WORD',
    RECORD_USER_ANSWER: 'RECORD_USER_ANSWER',
    USER_TYPED_ANSWER: 'USER_TYPED_ANSWER',
    CLEAR_VOCABULARY: 'CLEAR_VOCABULARY',
    VOCABULARY_SHOW_ANSWER_MODAL: 'VOCABULARY_SHOW_ANSWER_MODAL',
    VOCABULARY_CLOSE_ANSWER_MODAL: 'VOCABULARY_CLOSE_ANSWER_MODAL',
};

export default aTypes;