const aTypes = {
    AUTH_EMAIL_FIELD_CHANGE: 'AUTH_EMAIL_FIELD_CHANGE',
    AUTH_PASSWORD_FIELD_CHANGE: 'AUTH_PASSWORD_FIELD_CHANGE',
    AUTH_CLEAR_FIELDS: 'AUTH_CLEAR_FIELDS',
    AUTH_MODAL_CLOSE: 'AUTH_MODAL_CLOSE',
    AUTH_USER_IS_LOGGED: 'AUTH_USER_IS_LOGGED',
    SEND_REQUEST_FOR_AUTH: 'SEND_REQUEST_FOR_AUTH',
    SEND_REQUEST_FOR_AUTH_REJECT: 'SEND_REQUEST_FOR_AUTH_REJECT',
    HEADER_GET_DATA: 'HEADER_GET_DATA',
    AUTH_MODAL_LOADING: 'AUTH_MODAL_LOADING',
    AUTH_MODAL_LOADING_REJECT: 'AUTH_MODAL_LOADING_REJECT',
    AUTH_MODAL_CLEAR_ERROR: 'AUTH_MODAL_CLEAR_ERROR',
};

export default aTypes;