const aTypes = {
    AUTH_EMAIL_FIELD_CHANGE: 'AUTH_EMAIL_FIELD_CHANGE',
    AUTH_PASSWORD_FIELD_CHANGE: 'AUTH_PASSWORD_FIELD_CHANGE',
    AUTH_CLEAR_FIELDS: 'AUTH_CLEAR_FIELDS',
    AUTH_MODAL_CLOSE: 'AUTH_MODAL_CLOSE',
    SEND_REQUEST_FOR_AUTH: 'SEND_REQUEST_FOR_AUTH',
    SEND_REQUEST_FOR_AUTH_REJECT: 'SEND_REQUEST_FOR_AUTH_REJECT',
};

export default aTypes;