const aTypes = {
    AUTH_MODAL_OPEN: 'AUTH_MODAL_OPEN',
    AUTH_MODAL_CLOSE: 'AUTH_MODAL_CLOSE',
    EMAIL_FIELD_UPDATE: 'EMAIL_FIELD_UPDATE',
    PASSWORD_FIELD_UPDATE: 'PASSWORD_FIELD_UPDATE',
    SHOW_PASSWORD_FIELD: 'SHOW_PASSWORD_FIELD'
};

export default aTypes;