const aTypes = {
    AUTH_OPEN: 'AUTH_OPEN',
    AUTH_OPEN_FULFILLED: 'AUTH_OPEN_FULFILLED',
    AUTH_OPEN_REJECTED: 'AUTH_OPEN_REJECTED',
    AUTH_CLOSE: 'AUTH_CLOSE',
    AUTH_CLOSE_FULFILLED: 'AUTH_CLOSE_FULFILLED',
    AUTH_CLOSE_REJECTED: 'AUTH_CLOSE_REJECTED',
    FORM_FIELDS_UPDATE: 'FORM_FIELDS_UPDATE',
    FORM_FIELDS_UPDATE_FULFILLED: 'FORM_FIELDS_UPDATE_FULFILLED',
    FORM_FIELDS_UPDATE_REJECTED: 'FORM_FIELDS_UPDATE_REJECTED',
};

export default aTypes;